const ERROR_TYPES = {
  EMPTY: "EMPTY",
  BOTFILTER_TRIGGERED: "BOTFILTER_TRIGGERED",
  EMAIL_INVALID: "EMAIL_INVALID",
  MIN_LENGTH_INVALID: "MIN_LENGTH_INVALID",
  MAX_LENGTH_INVALID: "MAX_LENGTH_INVALID"
};

module.exports = Object.freeze(ERROR_TYPES);